# Generated by Django 4.2.13 on 2024-09-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created',), 'permissions': [('post', 'Can change add a blog'), ('edit', 'Can edit a blog'), ('delete', 'Can delete a blog')]},
        ),
    ]
