# Generated by Django 5.0.3 on 2024-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_description',
            field=models.CharField(default='vase', max_length=250),
            preserve_default=False,
        ),
    ]
