# Generated by Django 4.2.13 on 2024-11-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created',), 'permissions': [('do_some_blog', 'Can change add a blog'), ('do_all_blog', 'Can change add a blog')]},
        ),
    ]
