# Generated by Django 4.2.13 on 2024-08-21 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('product_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_image/')),
                ('description', models.TextField()),
                ('recent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('recent',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('destination', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.SlugField(unique=True)),
                ('invoice_total', models.PositiveIntegerField()),
                ('transport_price', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField()),
                ('include_transport', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('destitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Item_images',
            fields=[
                ('item_id', models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='rose', max_length=250)),
                ('addphotos', models.ImageField(upload_to='display_image/')),
                ('item_image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('item_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.item')),
                ('quantity', models.PositiveIntegerField()),
                ('in_cart', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order')),
            ],
        ),
    ]
