# Generated by Django 4.2.13 on 2024-11-02 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='product_image/')),
                ('description', models.TextField()),
                ('recent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('recent',),
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('destination', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('include_transport', models.BooleanField(default=False)),
                ('invoice_total', models.PositiveIntegerField(default=0)),
                ('transport_price', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'OPEN'), ('clearing', 'CLEARING'), ('closed', 'CLOSED')], max_length=200)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destitation', models.ForeignKey(default=shop.models.get_default_transport, on_delete=django.db.models.deletion.CASCADE, to='shop.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Item_images',
            fields=[
                ('item_id', models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='rose', max_length=250)),
                ('addphotos', models.ImageField(upload_to='display_image/')),
                ('item_image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
