# Generated by Django 5.0.3 on 2024-03-11 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('recent',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.SlugField(max_length=250, unique_for_date='recent'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
