# Generated by Django 4.2.13 on 2024-10-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
