# Generated by Django 4.2.13 on 2024-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cart_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('processing', 'PROCESSING'), ('transporting', 'TRANSPORTING'), ('closed', 'CLOSED')], max_length=200),
        ),
    ]
