# Generated by Django 4.2.13 on 2024-11-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('recent',), 'permissions': [('can_do_all_item', 'Can do all modifications to Items')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_do_all_order', 'Can do all modifications to order')]},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'permissions': [('can_do_all_transport', 'Can do all modifications to transport')]},
        ),
    ]
