# Generated by Django 5.0.3 on 2024-03-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_images',
            old_name='name',
            new_name='item_image_name',
        ),
    ]
