# Generated by Django 4.2.13 on 2024-11-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destitation',
            field=models.OneToOneField(default='nowhere', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.transport'),
        ),
    ]
