# Generated by Django 5.0.3 on 2024-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_name_item_images_item_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_images',
            name='display_name',
            field=models.CharField(default='rose', max_length=250),
        ),
    ]
