# Generated by Django 4.2.13 on 2024-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_item_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
