# Generated by Django 5.0.3 on 2024-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_images_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_images',
            name='addphotos',
            field=models.ImageField(upload_to='display_image/'),
        ),
    ]
