# Generated by Django 4.2.13 on 2024-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'OPEN'), ('processing', 'PROCESSING'), ('transporting', 'TRANSPORTING'), ('delivered', 'DELIVERED')], max_length=200),
        ),
    ]
