# Generated by Django 5.0.3 on 2024-05-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_item_images_addphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('item_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('in_cart', models.BooleanField(default=False)),
                ('item_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
