# Generated by Django 5.0.3 on 2024-05-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='item_id',
            new_name='wish_id',
        ),
    ]
