# Generated by Django 5.0.3 on 2024-05-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_item_id_wishlist_wish_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wish_id',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='item_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.item'),
        ),
    ]
