# Generated by Django 5.0.3 on 2024-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_wishlist_wish_id_alter_wishlist_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(max_length=250, unique=True),
        ),
    ]
