# Generated by Django 5.0.3 on 2024-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_item_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
