# Generated by Django 4.2.13 on 2024-06-12 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_item_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.SlugField(unique=True)),
                ('invoice_total', models.PositiveIntegerField()),
                ('grand_total', models.PositiveIntegerField()),
                ('include_transport', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('Bahati', 'Bahati, Nakuru'), ('Naka', 'Naka, Nakuru'), ('Pipeline', 'Pipeline, Nakuru')], default='Naka', max_length=250)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
