# Generated by Django 4.2.13 on 2024-06-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_transport_alter_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='id',
        ),
        migrations.AlterField(
            model_name='transport',
            name='destination',
            field=models.CharField(choices=[('Bahati', 'Bahati, Nakuru'), ('Naka', 'Naka, Nakuru'), ('Pipeline', 'Pipeline, Nakuru')], default='Naka', max_length=250, primary_key=True, serialize=False),
        ),
    ]
