# Generated by Django 4.2.13 on 2024-06-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
    ]
