# Generated by Django 4.2.13 on 2024-06-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_wishlist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.transport'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_price',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
    ]
