# Generated by Django 4.2.13 on 2024-07-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_destitation_order_transport_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transport_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
