# Generated by Django 4.2.13 on 2024-09-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('promote', 'Can change add a blog'), ('demote', 'Can edit a blog')]},
        ),
        migrations.AlterField(
            model_name='profile',
            name='mpesa_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
